<?php

$model = new app\models\Kpb();
echo "<div class=\"easyui-layout\" style=\"width:100%;height:100%;\">\n    <div data-options=\"region:'north'\" style=\"height:50%;overflow: hidden\">\n        <table id=\"tt\"\n               class=\"easyui-datagrid\" style=\"width:100%;height:100%\"\n               url=\"";
echo yii\helpers\Url::to(array("list-data"));
echo "\"\n               title=\"Setting Nilai Kartu KPB\"\n               singleselect=\"true\"\n               rownumbers=\"true\" pagination=\"true\">\n            <thead>\n            <tr>\n                <th field=\"kode\" width=\"100\">Kode</th>\n                <th field=\"nama\" width=\"250\">Nama</th>\n                <th field=\"harga_ass_1\" width=\"100\" align=\"right\" formatter=\"formatMoney\">Harga Ass #1</th>\n                <th field=\"harga_ass_2\" width=\"100\" align=\"right\" formatter=\"formatMoney\">Harga Ass #2</th>\n                <th field=\"harga_ass_3\" width=\"100\" align=\"right\" formatter=\"formatMoney\">Harga Ass #3</th>\n                <th field=\"harga_ass_4\" width=\"100\" align=\"right\" formatter=\"formatMoney\">Harga Ass #4</th>\n                <th field=\"harga_oli\" width=\"100\" align=\"right\" formatter=\"formatMoney\">Harga Oli</th>\n            </tr>\n            </thead>\n        </table>\n    </div>\n    <div data-options=\"region:'center'\" style=\"height:40%;padding: 10px 20px\">\n        <form id=\"form\" method=\"post\" action=\"\">\n            <div class=\"form-control\">\n                <div class=\"form-control\">\n                    ";
echo app\components\EasyUI::input($model, "kode", 300);
echo "                </div>\n                <div class=\"form-control\">\n                    ";
echo app\components\EasyUI::input($model, "nama", 300);
echo "                </div>\n                <div class=\"form-control\">\n                    ";
echo app\components\EasyUI::number($model, "harga_ass_1", 300);
echo "                </div>\n                <div class=\"form-control\">\n                    ";
echo app\components\EasyUI::number($model, "harga_ass_2", 300);
echo "                </div>\n                <div class=\"form-control\">\n                    ";
echo app\components\EasyUI::number($model, "harga_ass_3", 300);
echo "                </div>\n                <div class=\"form-control\">\n                    ";
echo app\components\EasyUI::number($model, "harga_ass_4", 300);
echo "                </div>\n                <div class=\"form-control\">\n                    ";
echo app\components\EasyUI::number($model, "harga_oli", 300);
echo "                </div>\n            </div>\n        </form>\n    </div>\n    <div data-options=\"region:'south'\" style=\"height:10%;padding: 10px 20px\">\n        <a href=\"javascript:void(0)\" id=\"btn-save\" class=\"easyui-linkbutton\"\n           data-options=\"iconCls:'icon-save'\">Simpan</a>\n        <a href=\"javascript:void(0)\" id=\"btn-delete\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-cancel'\">Hapus</a>\n    </div>\n</div>\n\n<script>\n    var kpb = null;\n\n    \$(\"#tt\").datagrid({\n        toolbar: addSearchToolbar('tt'),\n        onClickRow: function (index, row) {\n            kpb = row;\n\n            console.log(row);\n            temporaryData = row;\n\n            for (var property in kpb) {\n                if (kpb.hasOwnProperty(property)) {\n                    //console.log(property, selectedData[property])\n                    \$(\"#\" + property).setValue(kpb[property]);\n                }\n            }\n        }\n    });\n\n    \$(\"#btn-add\").linkbutton({\n        onClick: function () {\n            \$(\"#form\").form('reset');\n            kpb = null;\n        }\n    });\n\n    \$(\"#btn-save\").linkbutton({\n        onClick: function () {\n            var serialize = {\n                Kpb: {\n                    kode: \$(\"#kode\").textbox('getValue'),\n                    nama: \$(\"#nama\").textbox('getValue'),\n                    harga_ass_1: parseInt(\$(\"#harga_ass_1\").numberbox('getValue')),\n                    harga_ass_2: parseInt(\$(\"#harga_ass_2\").numberbox('getValue')),\n                    harga_ass_3: parseInt(\$(\"#harga_ass_3\").numberbox('getValue')),\n                    harga_ass_4: parseInt(\$(\"#harga_ass_4\").numberbox('getValue')),\n                    harga_oli: parseInt(\$(\"#harga_oli\").numberbox('getValue'))\n                }\n            };\n            console.log(serialize);\n            \$.ajax({\n                url: \"";
echo yii\helpers\Url::to(array("save"));
echo "\" + (kpb == null ? \"\" : \"?id=\" + kpb.id),\n                data: serialize,\n                type: \"post\",\n                dataType: \"json\",\n                success: function (msg) {\n                    if (msg.status == 200) {\n                        dialog(\"Simpan Data Sukses\");\n                        \$('#tt').datagrid('reload');\n                    }\n                },\n                error: function (xhr, ajaxOptions, thrownError) {\n                    dialog(xhr.responseJSON.message);\n                }\n            });\n            return false;\n        }\n    });\n\n    \$(\"#btn-delete\").click(function () {\n        \$.ajax({\n            url: \"";
echo yii\helpers\Url::to(array("delete"));
echo "?id=\" + kpb.id,\n            success: function (msg) {\n                dialog(\"Hapus Data Sukses\");\n                \$('#tt').datagrid('reload');\n                \$(\"#form\").form(\"clear\");\n                kpb = null;\n            }\n        });\n        return false;\n    });\n\n    setTitle(\"Setting KPB\");\n</script>";

?>