<?php

echo "<div class=\"easyui-layout\" style=\"width:100%;height:100%;\">\n    <div data-options=\"region:'west',border:false\" style=\"width:50%\">\n        <table id=\"list_konsumen\" style=\"height:100%;width: 100%\">\n            <thead>\n            <tr>\n                <th field=\"nopol\" width=\"80\" align=\"center\">NOPOL</th>\n                <th field=\"nama_identitas\" width=\"150\">Nama Identitas</th>\n                <th field=\"nama_pengguna\" width=\"150\">Nama Pengguna</th>\n                <th field=\"alamat\" width=\"150\">Alamat</th>\n                <th field=\"no_telepon\" width=\"80\" align=\"center\">No Telp</th>\n            </tr>\n            </thead>\n        </table>\n    </div>\n    <div data-options=\"region:'east',border:false\" style=\"width:50%\">\n        <div class=\"easyui-layout\" style=\"width:100%;height:100%;\">\n            <div data-options=\"region:'north',border:false\" style=\"height:50%\">\n                <table id=\"list_jasa\" style=\"height:100%;width: 100%\">\n                    <thead>\n                    <tr>\n                        <th field=\"pkb_tanggal\" width=\"80\" align=\"center\">Tgl Service</th>\n                        <th field=\"pkb_km\" width=\"80\" align=\"right\">KM</th>\n                        <th field=\"pkb_karyawan\" width=\"120\" align=\"center\">Mekanik</th>\n                        <th field=\"pkb_no\" width=\"120\" align=\"center\">No PKB</th>\n                        <th field=\"jasa_kode\" width=\"80\">Kode Jasa</th>\n                        <th field=\"jasa_nama\" width=\"250\">Keterangan</th>\n                    </tr>\n                    </thead>\n                </table>\n            </div>\n            <div data-options=\"region:'south',border:false\" style=\"height:50%\">\n                <table id=\"list_suku_cadang\" style=\"height:100%;width: 100%\">\n                    <thead>\n                    <tr>\n                        <th field=\"pkb_tanggal\" width=\"80\" align=\"center\">Tgl Pembelian</th>\n                        <th field=\"pkb_km\" width=\"80\" align=\"right\">KM</th>\n                        <th field=\"pkb_karyawan\" width=\"120\" align=\"center\">Mekanik</th>\n                        <th field=\"pkb_no\" width=\"120\" align=\"center\">No PKB</th>\n                        <th field=\"suku_cadang_kode\" width=\"100\">Kode Part</th>\n                        <th field=\"suku_cadang_nama\" width=\"250\">Keterangan</th>\n                    </tr>\n                    </thead>\n                </table>\n            </div>\n        </div>\n    </div>\n</div>\n\n<script>\n    \$(\"#list_konsumen\").datagrid({\n        url: \"";
echo yii\helpers\Url::to(array("list-konsumen"));
echo "\",\n        singleSelect: true,\n        pagination: true,\n        rownumbers: true,\n        fitColumns: true,\n        pageSize: 20,\n        toolbar: addSearchToolbar('list_konsumen'),\n        onClickRow: function(index, row){\n            \$(\"#list_jasa\").datagrid('load', \"";
echo yii\helpers\Url::to(array("list-jasa", "id" => ""));
echo "\" + row.id);\n            \$(\"#list_suku_cadang\").datagrid('load', \"";
echo yii\helpers\Url::to(array("list-suku-cadang", "id" => ""));
echo "\" + row.id);\n        }\n    });\n\n    \$(\"#list_jasa\").datagrid({\n        url: \"";
echo yii\helpers\Url::to(array("list-jasa"));
echo "\",\n        singleSelect: true,\n        pagination: true,\n        rownumbers: true,\n        fitColumns: true,\n    });\n\n    \$(\"#list_suku_cadang\").datagrid({\n        url: \"";
echo yii\helpers\Url::to(array("list-suku-cadang"));
echo "\",\n        singleSelect: true,\n        pagination: true,\n        rownumbers: true,\n        fitColumns: true,\n    });\n\n    setTitle(\"Historikal Konsumen\");\n</script>";

?>