<?php

$model = new app\models\Motor();
echo "<div class=\"easyui-layout\" style=\"width:100%;height:100%;\">\n    <div data-options=\"region:'north'\" style=\"height:50%;overflow: hidden\">\n        <table id=\"tt\"\n               class=\"easyui-datagrid\" style=\"width:100%;height:100%\"\n               url=\"";
echo yii\helpers\Url::to(array("list-data"));
echo "\"\n               title=\"Data Motor\"\n               singleselect=\"true\"\n               rownumbers=\"true\" pagination=\"true\">\n            <thead>\n            <tr>\n                <th field=\"kode\" width=\"80\">Kode</th>\n                <th field=\"merek_nama\" width=\"100\">Merek</th>\n                <th field=\"nama\" width=\"300\">Nama</th>\n                <th field=\"warna\" width=\"150\">Warna</th>\n                <th field=\"motor_group_nama\" width=\"120\">Group</th>\n                <th field=\"motor_jenis_nama\" width=\"120\">Jenis</th>\n            </tr>\n            </thead>\n        </table>\n    </div>\n    <div data-options=\"region:'center'\" style=\"height:40%;padding: 10px 20px\">\n        <form id=\"form\" method=\"post\" action=\"\">\n            <div class=\"form-control\">\n                <div class=\"form-control\">\n                    ";
echo app\components\EasyUI::input($model, "kode", 300);
echo "                </div>\n                <div class=\"form-control\">\n                    ";
echo app\components\EasyUI::combo($model, "merek_id", 300, yii\helpers\ArrayHelper::map(app\models\Merek::find()->all(), "id", "nama"));
echo "                </div>\n                <div class=\"form-control\">\n                    ";
echo app\components\EasyUI::input($model, "nama", 300);
echo "                </div>\n                <div class=\"form-control\">\n                    ";
echo app\components\EasyUI::input($model, "warna", 300);
echo "                </div>\n                <div class=\"form-control\">\n                    ";
echo app\components\EasyUI::combo($model, "motor_group_id", 300, yii\helpers\ArrayHelper::map(app\models\MotorGroup::find()->all(), "id", "nama"));
echo "                </div>\n                <div class=\"form-control\">\n                    ";
echo app\components\EasyUI::combo($model, "motor_jenis_id", 300, yii\helpers\ArrayHelper::map(app\models\MotorJenis::find()->all(), "id", "nama"));
echo "                </div>\n            </div>\n        </form>\n    </div>\n    <div data-options=\"region:'south'\" style=\"height:10%;padding: 10px 20px\">\n        <button id=\"btn-add\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add'\">Tambah Baru</button>\n        <button id=\"btn-save\" class=\"easyui-linkbutton\" data-options=\"iconCls:'fam disk'\">Simpan</button>\n        <button id=\"btn-delete\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-cancel'\">Hapus</button>\n    </div>\n</div>\n\n<script>\n    var motor = null;\n\n    \$(\"#tt\").datagrid({\n        toolbar: addSearchToolbar('tt'),\n        onClickRow: function (index, row) {\n            motor = row;\n\n            for (var property in motor) {\n                if (motor.hasOwnProperty(property)) {\n                    //console.log(property, selectedData[property])\n                    \$(\"#\" + property).setValue(motor[property]);\n                }\n            }\n        }\n    });\n\n    \$(\"#btn-add\").linkbutton({\n        onClick: function () {\n            \$(\"#form\").form('reset');\n            motor = null;\n        }\n    });\n\n    \$(\"#btn-save\").linkbutton({\n        onClick: function () {\n            var serialize = \$(\"#form\").serialize();\n            console.log(serialize);\n            \$.ajax({\n                url: \"";
echo yii\helpers\Url::to(array("save"));
echo "\" + (motor == null ? \"\" : \"?id=\" + motor.id),\n                data: serialize,\n                type: \"post\",\n                dataType: \"json\",\n                success: function (msg) {\n                    if(msg.status == 200) {\n                        dialog(\"Simpan Data Sukses\");\n                        \$('#tt').datagrid('reload');\n                    }\n                },\n                error: function(xhr, ajaxOptions, thrownError){\n                    dialog(xhr.responseJSON.message);\n                }\n            });\n            return false;\n        }\n    });\n\n    \$(\"#btn-delete\").click(function () {\n        \$.ajax({\n            url: \"";
echo yii\helpers\Url::to(array("delete"));
echo "?id=\" + motor.id,\n            success: function (msg) {\n                dialog(\"Hapus Data Sukses\");\n                \$('#tt').datagrid('reload');\n                \$(\"#form\").form(\"clear\");\n                motor = null;\n            }\n        });\n        return false;\n    });\n\n    setTitle(\"Motor\");\n</script>";

?>