<?php

echo "<div class=\"easyui-layout\" style=\"width:100%;height:100%;\">\n    <!--\n    <div data-options=\"region:'north',border:false\" style=\"height:50px;padding: 10px;overflow: hidden\">\n\n    </div>\n    -->\n    <div data-options=\"region:'center',border:false\" style=\"padding: 10px\">\n        <table id=\"list_pekerjaan\" style=\"height:100%\">\n            <thead>\n            <tr>\n                <th field=\"nomor\" width=\"150\">No PKB</th>\n                <th field=\"waktu_daftar_date\" width=\"100\" align=\"center\">Tgl Service</th>\n                <th field=\"tanggal_ass\" width=\"100\" align=\"center\">Tgl KPB</th>\n                <th field=\"konsumen_nopol\" width=\"100\" align=\"center\">No Polisi</th>\n                <th field=\"km\" width=\"80\" align=\"right\">KM</th>\n                <th field=\"karyawan_nama\" width=\"120\">Mekanik</th>\n                <th field=\"durasi_service\" width=\"120\">Durasi (mnt)</th>\n                <th field=\"perintah_kerja_status_nama\" width=\"100\" align=\"center\">Status</th>\n                <th field=\"action_koreksi\" width=\"100\" align=\"center\">#</th>\n            </tr>\n            </thead>\n        </table>\n    </div>\n</div>\n\n<div id=\"dialog_edit_perintah_kerja\" class=\"easyui-window\" style=\"padding: 10px 20px\">\n    <div class=\"form-control\">\n        <input id=\"tanggal_ass\" class=\"easyui-datebox\" label=\"Tgl KPB:\" labelWidth=\"150px\" style=\"width:300px\">\n    </div>\n    <div class=\"form-control\">\n        <input id=\"km\" class=\"easyui-numberbox\" label=\"KM:\" labelWidth=\"150px\" style=\"width:240px\">\n    </div>\n    <div class=\"form-control\">\n        <input id=\"durasi_service\" class=\"easyui-numberbox\" label=\"Durasi:\" labelWidth=\"150px\" style=\"width:240px\">\n    </div>\n    <div class=\"form-control\">\n        ";
echo yii\helpers\Html::dropDownList("karyawan_id", NULL, yii\helpers\ArrayHelper::map(app\models\User::getCurrentActive(), "id", "name"), array("class" => "easyui-combobox", "id" => "karyawan_id", "label" => "Mekanik:", "labelWidth" => "150px", "style" => "width:400px"));
echo "    </div>\n    <div style=\"margin-top: 20px;padding-left: 180px\">\n        <button id=\"btn_simpan_detail\" class=\"easyui-linkbutton\" iconCls=\"fam disk\">Simpan</button>\n    </div>\n</div>\n\n<script>\n    //Search pengeluaran\n    \$(\"#dialog_edit_perintah_kerja\").window({\n        width: 480,\n        height: 250,\n        modal: true,\n        closed: true,\n        title: \"Edit Detail\"\n    });\n\n    \$.parser.parse(\"#dialog_edit_perintah_kerja\");\n\n    var pkb_id = null;\n\n    \$(document).off(\"click\", \".btn-edit\");\n    \$(document).on(\"click\", \".btn-edit\", function(){\n        \$(\"#dialog_edit_perintah_kerja\").window('open');\n\n        pkb_id = \$(this).attr(\"data_id\");\n\n        \$.ajax({\n            url : \"";
echo yii\helpers\Url::to(array("load"));
echo "?id=\" + pkb_id,\n            dataType: \"json\",\n            success: function(data){\n                console.log(data);\n\n                \$(\"#tanggal_ass\").datebox(\"setValue\", data.tanggal_ass);\n                \$(\"#km\").numberbox(\"setValue\", data.km);\n                \$(\"#durasi_service\").numberbox(\"setValue\", data.durasi_service);\n                \$(\"#karyawan_id\").combobox(\"select\", data.karyawan_id);\n            }\n        });\n    });\n\n    \$(\"#list_pekerjaan\").datagrid({\n        toolbar: addSearchToolbar('list_pekerjaan'),\n        url: \"";
echo yii\helpers\Url::to(array("list-pekerjaan"));
echo "\",\n        singleSelect: true,\n        pagination: true,\n        rownumbers: true,\n        fitColumns: true\n    });\n\n    \$(\"#btn_simpan_detail\").linkbutton({\n        onClick: function(){\n            \$.ajax({\n                url : \"";
echo yii\helpers\Url::to(array("save"));
echo "?id=\" + pkb_id,\n                data : {\n                    tanggal_ass : \$(\"#tanggal_ass\").datebox(\"getValue\"),\n                    km : \$(\"#km\").numberbox(\"getValue\"),\n                    durasi_service : \$(\"#durasi_service\").numberbox(\"getValue\"),\n                    karyawan_id : \$(\"#karyawan_id\").combobox(\"getValue\")\n                },\n                type : \"post\",\n                dataType: \"json\",\n                success: function(data){\n                    \$(\"#dialog_edit_perintah_kerja\").window('close');\n                    \$(\"#list_pekerjaan\").datagrid('reload');\n                }\n            });\n        }\n    });\n\n    setTitle(\"Koreksi PKB\");\n</script>";

?>