<?php

app\components\LbbHelper::setDate($_GET["tanggal1"], $_GET["tanggal2"]);
$operasional = 0;
$hariKerja = app\models\HariAktif::find()->where(array("jaringan_id" => app\models\Jaringan::getCurrentID()))->andWhere("tanggal between '" . $_GET["tanggal1"] . "' AND '" . $_GET["tanggal2"] . "'")->count();
$jumlahPkb = app\models\PerintahKerja::find()->where(array("jaringan_id" => app\models\Jaringan::getCurrentID()))->andWhere("waktu_daftar between '" . $_GET["tanggal1"] . " 00:00:00' AND '" . $_GET["tanggal2"] . " 23:59:59' ")->count();
$perHari = 0;
if ($hariKerja != 0) {
    $perHari = floor($jumlahPkb / $hariKerja);
}
echo "<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n    <tr>\n        <td style=\"\">III. LAPORAN PENGELUARAN OPERASIONAL BENGKEL</td>\n        <td style=\"width:100px\"></td>\n        <td style=\"width:200px;border: 1px solid #000;text-align: right\">";
echo app\components\Angka::toReadableAngka($operasional, false);
echo "</td>\n    </tr>\n    <tr>\n        <td>IV. JUMLAH HARI KERJA DALAM BULAN INI</td>\n        <td></td>\n        <td style=\"border: 1px solid #000;text-align: right\">";
echo $hariKerja;
echo " HARI</td>\n    </tr>\n    <tr>\n        <td>V. RATA-RATA UNIT PER HARI DALAM BULAN INI</td>\n        <td></td>\n        <td style=\"border: 1px solid #000;text-align: right\">";
echo $perHari;
echo " UNIT/HARI</td>\n    </tr>\n    <tr>\n        <td colspan=\"3\">VI. LAPORAN PRESTASI MEKANIK DALAM BULAN INI</td>\n    </tr>\n</table>\n<br>\n<br>\n<style type=\"text/css\">\n    body {\n        font-family: \"Courier New\", Courier, monospace;\n        font-size: 12px;\n    }\n\n    td {\n        padding-left: 5px;\n        padding-right: 5px;\n        font-size: 11px;\n    }\n\n    .tg  {border-collapse:collapse;border-spacing:0;}\n    .tg td{font-family:Arial, sans-serif;font-size:12px;padding:0px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}\n    .tg th{font-family:Arial, sans-serif;font-size:12px;font-weight:normal;padding:0px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}\n    .tg .tg-s6z2{text-align:center;width: 4%}\n</style>\n<table class=\"tg\" style=\"width: 100%\">\n    <tr>\n        <th rowspan=\"3\" style=\"text-align: center\">No</th>\n        <th class=\"\" rowspan=\"3\" style=\"width: 36%\">Mekanik</th>\n        <th class=\"tg-s6z2\" rowspan=\"3\">Jumlah Unit Diservice</th>\n        <th class=\"tg-s6z2\" rowspan=\"3\">Tidak Hadir<br>(Hari)</th>\n        <th class=\"tg-s6z2\" rowspan=\"3\">Hadir<br>(Hari)</th>\n        <th class=\"tg-s6z2\" rowspan=\"3\">Jam<br>Tersedia</th>\n        <th class=\"tg-s6z2\" colspan=\"9\">Jenis Pekerjaan</th>\n        <th class=\"tg-s6z2\" rowspan=\"3\">Jam<br>Dipakai</th>\n    </tr>\n    <tr>\n        <td class=\"tg-s6z2\" rowspan=\"2\">KPB</td>\n        <td class=\"tg-s6z2\" rowspan=\"2\">Claim<br>C2</td>\n        <td class=\"tg-s6z2\" colspan=\"3\">Quick Service</td>\n        <td class=\"tg-s6z2\" rowspan=\"2\">L.R</td>\n        <td class=\"tg-s6z2\" rowspan=\"2\">H.R</td>\n        <td class=\"tg-s6z2\" rowspan=\"2\">Total</td>\n        <td class=\"tg-s6z2\" rowspan=\"2\">JR</td>\n    </tr>\n    <tr>\n        <td class=\"tg-s6z2\">CS</td>\n        <td class=\"tg-s6z2\">LS</td>\n        <td class=\"tg-s6z2\">GO</td>\n    </tr>\n    ";
$no = 1;
$tj1 = 0;
$tj2 = 0;
$tj3 = 0;
$tj4 = 0;
$tj5 = 0;
$tp1 = 0;
$tp2 = 0;
$tp3 = 0;
$tp4 = 0;
$tp5 = 0;
$tp6 = 0;
$tp7 = 0;
$tp8 = 0;
$tpTot = 0;
foreach (app\models\User::find()->where(array("jaringan_id" => app\models\Jaringan::getCurrentID(), "role_id" => app\models\Role::MEKANIK, "status" => 1))->all() as $mekanik) {
    $presensi = app\components\LbbHelper::getPresensi($mekanik->id);
    echo "    <tr>\n        <td style=\"width: 5%;text-align: center\"><nobr>";
    echo $no;
    echo "</nobr></td> <!-- No -->\n        <td class=\"\" style=\"text-align: left\">";
    echo $mekanik->name;
    echo "</td><!-- Nama -->\n        <td class=\"tg-s6z2\">";
    echo $j1 = app\components\LbbHelper::getMekanikUnitService($mekanik->id);
    echo "</td>\n        <td class=\"tg-s6z2\">";
    echo $j2 = $presensi["absen"];
    echo "</td>\n        <td class=\"tg-s6z2\">";
    echo $j3 = $presensi["hadir"];
    echo "</td>\n        <td class=\"tg-s6z2\">";
    echo $j4 = app\components\LbbHelper::getMekanikJamTersedia($mekanik->id);
    echo "</td>\n        <td class=\"tg-s6z2\">";
    echo $p1 = app\components\LbbHelper::getMekanikJasa($mekanik->id, array(app\models\JasaGroup::ASS1, app\models\JasaGroup::ASS2, app\models\JasaGroup::ASS3, app\models\JasaGroup::ASS4));
    echo "</td>\n        <td class=\"tg-s6z2\">";
    echo $p2 = app\components\LbbHelper::getMekanikJasa($mekanik->id, array(app\models\JasaGroup::CL));
    echo "</td>\n        <td class=\"tg-s6z2\">";
    echo $p3 = app\components\LbbHelper::getMekanikJasa($mekanik->id, array(app\models\JasaGroup::PL));
    echo "</td>\n        <td class=\"tg-s6z2\">";
    echo $p4 = app\components\LbbHelper::getMekanikJasa($mekanik->id, array(app\models\JasaGroup::PR));
    echo "</td>\n        <td class=\"tg-s6z2\">";
    echo $p5 = app\components\LbbHelper::getMekanikJasa($mekanik->id, array(app\models\JasaGroup::GO));
    echo "</td>\n        <td class=\"tg-s6z2\">";
    echo $p6 = app\components\LbbHelper::getMekanikJasa($mekanik->id, array(app\models\JasaGroup::LR, app\models\JasaGroup::PR));
    echo "</td>\n        <td class=\"tg-s6z2\">";
    echo $p7 = app\components\LbbHelper::getMekanikJasa($mekanik->id, array(app\models\JasaGroup::HR, app\models\JasaGroup::PL));
    echo "</td>\n        <td class=\"tg-s6z2\">";
    echo $p1 + $p2 + $p3 + $p4 + $p5 + $p6 + $p7;
    echo "</td>\n        <td class=\"tg-s6z2\">";
    echo $p8 = app\components\LbbHelper::getMekanikJasa($mekanik->id, array(app\models\JasaGroup::JR));
    echo "</td>\n        <td class=\"tg-s6z2\">";
    echo $j5 = app\components\LbbHelper::getMekanikJamTerpakai($mekanik->id);
    echo "</td>\n    </tr>\n    ";
    $tj1 += $j1;
    $tj2 += $j2;
    $tj3 += $j3;
    $tj4 += $j4;
    $tj5 += $j5;
    $tp1 += $p1;
    $tp2 += $p2;
    $tp3 += $p3;
    $tp4 += $p4;
    $tp5 += $p5;
    $tp6 += $p6;
    $tp7 += $p7;
    $tp8 += $p8;
    $tpTot += $p1 + $p2 + $p3 + $p4 + $p5 + $p6 + $p7;
    $no++;
}
echo "    <tr>\n        <td class=\"tg-s6z2\" colspan=\"2\">Total</td>\n        <td class=\"tg-s6z2\">";
echo $tj1;
echo "</td>\n        <td class=\"tg-s6z2\">";
echo $tj2;
echo "</td>\n        <td class=\"tg-s6z2\">";
echo $tj3;
echo "</td>\n        <td class=\"tg-s6z2\">";
echo $tj4;
echo "</td>\n        <td class=\"tg-s6z2\">";
echo $tp1;
echo "</td>\n        <td class=\"tg-s6z2\">";
echo $tp2;
echo "</td>\n        <td class=\"tg-s6z2\">";
echo $tp3;
echo "</td>\n        <td class=\"tg-s6z2\">";
echo $tp4;
echo "</td>\n        <td class=\"tg-s6z2\">";
echo $tp5;
echo "</td>\n        <td class=\"tg-s6z2\">";
echo $tp6;
echo "</td>\n        <td class=\"tg-s6z2\">";
echo $tp7;
echo "</td>\n        <td class=\"tg-s6z2\">";
echo $tpTot;
echo "</td>\n        <td class=\"tg-s6z2\">";
echo $tp8;
echo "</td>\n        <td class=\"tg-s6z2\">";
echo $tj5;
echo "</td>\n    </tr>\n</table>\n<br>\n<br>\n<br>\n<table style=\"width: 99%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n    <tr>\n        <td style=\"width: 33%;text-align: center\">\n            Dibuat,\n            <br>\n            <br>\n            <br>\n            <br>\n            <br>\n            <br>\n            Frontdesk\n        </td>\n        <td style=\"width: 33%;text-align: center\">\n            Diperiksa,\n            <br>\n            <br>\n            <br>\n            <br>\n            <br>\n            <br>\n            Kepala Bengkel\n        </td>\n        <td style=\"width: 33%;text-align: center\">\n            Mengetahui,\n            <br>\n            <br>\n            <br>\n            <br>\n            <br>\n            <br>\n            Pemilik/Pimpinan\n        </td>\n    </tr>\n</table>";

?>