<?php

$model = new app\models\Gudang();
echo "<div class=\"easyui-layout\" style=\"width:100%;height:100%;\">\n    <div data-options=\"region:'north'\" style=\"height:50%;overflow: hidden\">\n        <table id=\"tt\"\n               class=\"easyui-datagrid\" style=\"width:100%;height:100%\"\n               url=\"";
echo yii\helpers\Url::to(array("list-data"));
echo "\"\n               title=\"Data Gudang\"\n               rownumbers=\"true\" pagination=\"true\">\n            <thead>\n                <tr>\n\t\t\t\t\t<th field=\"kode\" width=\"80\">Kode</th>\n\t\t\t\t\t<th field=\"nama\" width=\"200\">Nama</th>\n\t\t\t\t\t<th field=\"lokasi\" width=\"250\">Lokasi</th>\n\t\t\t\t\t</tr>\n            </thead>\n        </table>\n    </div>\n    <div data-options=\"region:'center'\" style=\"height:40%;padding: 10px 20px\">\n        <form id=\"form\" method=\"post\" action=\"\">\n            <div class=\"form-control\">\n\t\t\t\t<div class=\"form-control\">\n\t\t\t\t";
echo app\components\EasyUI::input($model, "kode", 300);
echo "\t\t\t\t</div>\n\t\t\t\t<div class=\"form-control\">\n\t\t\t\t";
echo app\components\EasyUI::input($model, "nama", 300);
echo "\t\t\t\t</div>\n\t\t\t\t<div class=\"form-control\">\n\t\t\t\t";
echo app\components\EasyUI::input($model, "lokasi", 300);
echo "\t\t\t\t</div>\n\t\t\t\t</div>\n        </form>\n    </div>\n    <div data-options=\"region:'south'\" style=\"height:10%;padding: 10px 20px\">\n        <button id=\"btn-add\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add'\">Tambah Baru</button>\n        <button id=\"btn-save\" class=\"easyui-linkbutton\" data-options=\"iconCls:'fam disk'\">Simpan</button>\n        <button id=\"btn-delete\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-cancel'\">Hapus</button>\n    </div>\n</div>\n\n<script>\n    var gudang = null;\n\n    \$(\"#tt\").datagrid({\n        singleSelect:true,\n        toolbar: addSearchToolbar('tt'),\n        onClickRow: function (index, row) {\n            gudang = row;\n\n            temporaryData = row;\n\n            for (var property in gudang) {\n                if (gudang.hasOwnProperty(property)) {\n                    //console.log(property, selectedData[property])\n                    \$(\"#\" + property).setValue(gudang[property]);\n                }\n            }\n        }\n    });\n\n    \$(\"#btn-add\").linkbutton({\n        onClick: function () {\n            \$(\"#form\").form('reset');\n            gudang = null;\n        }\n    });\n\n    \$(\"#btn-save\").linkbutton({\n        onClick: function () {\n            var serialize = \$(\"#form\").serialize();\n            console.log(serialize);\n            \$.ajax({\n                url: \"";
echo yii\helpers\Url::to(array("save"));
echo "\" + (gudang == null ? \"\" : \"?id=\" + gudang.id),\n                data: serialize,\n                type: \"post\",\n                dataType: \"json\",\n                success: function (msg) {\n                    if(msg.status == 200) {\n                        dialog(\"Simpan Data Sukses\");\n                        \$('#tt').datagrid('reload');\n                    }\n                },\n                error: function(xhr, ajaxOptions, thrownError){\n                    dialog(xhr.responseJSON.message);\n                }\n            });\n            return false;\n        }\n    });\n\n    \$(\"#btn-delete\").click(function () {\n        \$.ajax({\n            url: \"";
echo yii\helpers\Url::to(array("delete"));
echo "?id=\" + gudang.id,\n            success: function (msg) {\n                dialog(\"Hapus Data Sukses\");\n                \$('#tt').datagrid('reload');\n                \$(\"#form\").form(\"clear\");\n                gudang = null;\n            }\n        });\n        return false;\n    });\n\n    setTitle(\"Gudang\");\n</script>";

?>