<?php

echo "<div class=\"easyui-layout\" style=\"width:100%;height:100%;\">\n    <div data-options=\"region:'north',border:false\" style=\"height:20%;padding: 10px\">\n        <div class=\"form-control\">\n            ";
echo yii\helpers\Html::dropDownList("karyawan_id", NULL, yii\helpers\ArrayHelper::map(app\models\User::getCurrentActive(), "id", "kodeNama"), array("class" => "easyui-combobox", "id" => "karyawan_id", "label" => "Mekanik:", "labelWidth" => "100px", "style" => "width:300px"));
echo "            ";
echo yii\helpers\Html::dropDownList("absensi_status_id", NULL, yii\helpers\ArrayHelper::map(app\models\AbsensiStatus::find()->all(), "id", "nama"), array("class" => "easyui-combobox", "id" => "absensi_status_id", "style" => "width:100px"));
echo "        </div>\n        <div class=\"form-control\">\n            <input id=\"keterangan\" class=\"easyui-textbox\" label=\"Keterangan:\" labelWidth=\"100px\" style=\"width:400px\">\n        </div>\n        <div class=\"form-control\">\n            <button id=\"btn_simpan\" class=\"easyui-linkbutton\">Simpan</button>\n        </div>\n    </div>\n    <div data-options=\"region:'center',border:false\">\n        <table id=\"list_absensi_hari_ini\" style=\"height: 100%\">\n            <thead>\n            <tr>\n                <th field=\"tanggal\" width=\"150\" align=\"center\">Tanggal</th>\n                <th field=\"karyawan_nama\" width=\"150\">Nama Mekanik</th>\n                <th field=\"jam_masuk\" width=\"80\" align=\"center\">Jam Masuk</th>\n                <th field=\"jam_pulang\" width=\"80\" align=\"center\">Jam Pulang</th>\n                <th field=\"keterangan\" width=\"250\">Keterangan</th>\n                <th field=\"action\" width=\"100\" align=\"center\">#</th>\n            </tr>\n            </thead>\n        </table>\n    </div>\n</div>\n\n<script>\n    \$(\"#btn_simpan\").click(function(){\n        \$.ajax({\n            url : \"";
echo yii\helpers\Url::to(array("add-absensi"));
echo "\",\n            data : {\n                karyawan_id : \$(\"#karyawan_id\").val(),\n                absensi_status_id : \$(\"#absensi_status_id\").val(),\n                keterangan : \$(\"#keterangan\").val(),\n            },\n            type : \"post\",\n            dataType : \"json\",\n            success: function(msg){\n                if(msg.status == 200){\n                    dialog(\"Absensi berhasil ditambahkan.\");\n                    \$(\"#list_absensi_hari_ini\").datagrid('reload');\n                }else{\n                    dialog(msg.message);\n                }\n            },\n            error: function(xhr, ajaxOptions, thrownError){\n                dialog(xhr.responseJSON.message);\n            }\n        });\n    });\n\n    \$(\"#list_absensi_hari_ini\").datagrid({\n        url: \"";
echo yii\helpers\Url::to(array("list-absensi-hari-ini"));
echo "\",\n        singleSelect: true,\n        pagination: true,\n        rownumbers: true\n    });\n\n    \$(document).off(\"click\", \".btn-pulang\");\n    \$(document).on(\"click\", \".btn-pulang\", function(){\n        \$.ajax({\n            url : \"";
echo yii\helpers\Url::to(array("pulang"));
echo "?id=\" + \$(this).attr(\"data_id\"),\n            dataType: \"json\",\n            success: function () {\n                dialog(\"Absensi pulang berhasil.\");\n                \$(\"#list_absensi_hari_ini\").datagrid('reload');\n            },\n            error: function(xhr, ajaxOptions, thrownError){\n                dialog(xhr.responseJSON.message);\n            }\n        });\n    });\n\n    setTitle(\"Absensi Mekanik\");\n</script>";

?>