<?php

echo "<div class=\"easyui-layout\" style=\"width:100%;height:100%;\">\n    <div data-options=\"region:'north',border:false\" style=\"height:150px;padding: 10px\">\n        <div class=\"easyui-layout\" style=\"width:100%;height:100%;\">\n            <div data-options=\"region:'west',border:false\" style=\"width:50%;padding: 10px;overflow: hidden;\">\n                <div class=\"form-control\">\n                    <input id=\"tanggal_awal\" class=\"easyui-datebox\"\n                           label=\"Interval Waktu:\" labelWidth=\"100px\"\n                           style=\"width:200px\" value=\"";
echo date("Y-m-");
echo "01\">\n                    s/d\n                    <input id=\"tanggal_akhir\" class=\"easyui-datebox\"\n                           style=\"width:100px\" value=\"";
echo date("Y-m-d");
echo "\">\n                </div>\n                <div class=\"form-control\">\n                    ";
echo yii\helpers\Html::dropDownList("no_ass", NULL, array("" => "ALL", "ASS1", "ASS2", "ASS3", "ASS4"), array("class" => "easyui-combobox", "id" => "no_ass", "label" => "ASS ke-:", "labelWidth" => "100px", "style" => "width:220px"));
echo "                </div>\n                <div class=\"form-control\">\n                    ";
echo yii\helpers\Html::dropDownList("motor_id", NULL, yii\helpers\ArrayHelper::map(app\models\Motor::find()->all(), "id", "namaLengkap"), array("class" => "easyui-combobox", "id" => "motor_id", "label" => "Tipe Motor:", "labelWidth" => "100px", "style" => "width:500px", "prompt" => "ALL"));
echo "                </div>\n                <div class=\"form-control\">\n                    <input id=\"no_lkh\" class=\"easyui-textbox\" label=\"No LKH:\" labelWidth=\"100px\"\n                           style=\"width:300px\">\n                </div>\n            </div>\n            <div data-options=\"region:'east',border:false\" style=\"width:50%;padding: 10px;overflow: hidden;\">\n                <div class=\"form-control\">\n                    <input id=\"no_pkb\" disabled class=\"easyui-textbox\" label=\"No PKB:\" labelWidth=\"100px\"\n                           style=\"width:300px\">\n                </div>\n                <div class=\"form-control\">\n                    <input id=\"no_rangka\" disabled class=\"easyui-textbox\" label=\"No Rangka\" labelWidth=\"100px\"\n                           style=\"width:300px\">\n                </div>\n                <div class=\"form-control\">\n                    <input id=\"no_mesin\" disabled class=\"easyui-textbox\" label=\"No Mesin\" labelWidth=\"100px\"\n                           style=\"width:300px\">\n                </div>\n                <div class=\"form-control\">\n                    <input id=\"tanggal_service\" disabled class=\"easyui-datebox\"\n                           label=\"Tgl. Service:\" labelWidth=\"100px\"\n                           style=\"width:200px\" value=\"";
echo date("Y-m-d");
echo "\">\n                    <button id=\"btn_update\" disabled class=\"easyui-linkbutton\"\n                            data-options=\"iconCls:'fam disk'\">Update\n                    </button>\n                </div>\n            </div>\n        </div>\n    </div>\n    <div data-options=\"region:'center',border:false\" style=\"padding: 0px 10px 10px\">\n        <table id=\"list_kpb\" style=\"height:100%\">\n            <thead>\n            <tr>\n                <th field=\"tanggal_service_date\" width=\"100\" align=\"center\">Tgl Service</th>\n                <th field=\"no_pkb\" width=\"100\" align=\"center\">No PKB</th>\n                <th field=\"no_mesin\" width=\"100\">No Mesin</th>\n                <th field=\"nopol\" width=\"80\" align=\"center\">No Polisi</th>\n                <th field=\"motor_kode\" width=\"90\" align=\"center\">Kode Motor</th>\n                <th field=\"motor_nama\" width=\"150\">Nama Motor</th>\n                <th field=\"kpb_nama\" width=\"120\" align=\"center\">Group Kartu</th>\n                <th field=\"tanggal_beli\" width=\"80\" align=\"center\">Tgl Beli</th>\n                <th field=\"kpb_data\" width=\"60\" align=\"center\">KPB</th>\n                <th field=\"km\" width=\"60\" align=\"right\">KM</th>\n            </tr>\n            </thead>\n        </table>\n    </div>\n    <div data-options=\"region:'south',border:false\" style=\"height:100px;padding: 0px 10px 10px\">\n\n    </div>\n</div>\n\n<script>\n    var kpb = null;\n\n    \$(\"#list_kpb\").datagrid({\n        url: \"";
echo yii\helpers\Url::to(array("list-kpb"));
echo "\",\n        singleSelect: true,\n        pagination: true,\n        rownumbers: true,\n        fitColumns: true,\n        toolbar: addSearchToolbar(\"list_kpb\"),\n        onClickRow: function (index, row) {\n            console.log(row);\n            kpb = row;\n\n            \$(\"#no_pkb\").textbox('enable').textbox('setValue', row.no_pkb);\n            \$(\"#no_rangka\").textbox('enable').textbox('setValue', row.no_rangka);\n            \$(\"#no_mesin\").textbox('enable').textbox('setValue', row.no_mesin);\n            \$(\"#tanggal_service\").datebox('enable').datebox('setValue', row.tanggal_service_date);\n            \$(\"#btn_update\").linkbutton('enable');\n        }\n    });\n\n    \$(\"#tanggal_awal\").datebox({\n        onChange: function () {\n            reloadGrid();\n        }\n    });\n\n    \$(\"#tanggal_akhir\").datebox({\n        onChange: function () {\n            reloadGrid();\n        }\n    });\n\n    \$(\"#motor_id\").combobox({\n        onChange: function () {\n            reloadGrid();\n        }\n    });\n\n    function reloadGrid() {\n        \$(\"#list_kpb\").datagrid('load', \"";
echo yii\helpers\Url::to(array("list-kpb"));
echo "?tanggal1=\" + \$(\"#tanggal_awal\").datebox('getValue')\n            + \"&tanggal2=\" + \$(\"#tanggal_akhir\").datebox('getValue')\n            + \"&motor_id=\" + \$(\"#motor_id\").combobox('getValue'));\n    }\n\n    \$(\"#btn_update\").linkbutton({\n        onClick: function () {\n            \$.ajax({\n                url: \"";
echo yii\helpers\Url::to(array("update-kpb", "id" => ""));
echo "\" + kpb.pkb_id,\n                data: {\n                    no_pkb: \$(\"#no_pkb\").textbox('getValue'),\n                    no_rangka: \$(\"#no_rangka\").textbox('getValue'),\n                    no_mesin: \$(\"#no_mesin\").textbox('getValue'),\n                    tanggal_service: \$(\"#tanggal_service\").datebox('getValue')\n                },\n                type: \"post\",\n                dataType: \"json\",\n                success: function (msg) {\n                    dialog(msg.message);\n                    reloadGrid();\n                }\n            })\n        }\n    });\n\n    reloadGrid();\n</script>";

?>